### PR TITLE
Fix compute in HammingDistance object

### PR DESCRIPTION
**Pull request by nihsmik**
Hamming distance via bit sampling LSH is size of symmetric difference set.

### CODE REVIEW

**Comment by nihsmik** [comment]
The failed test is irrelevant to this pr.
I reported it: https://github.com/karlhigley/spark-neighbors/issues/46

**Comment by karlhigley** [comment]
That failing test may be flaky; agreed that it's irrelevant.

Could you add a test that demonstrates the difference between the current behavior and the new behavior, though? See [this test](https://github.com/karlhigley/spark-neighbors/blob/master/src/test/scala/com/github/karlhigley/spark/neighbors/DistanceMeasureSuite.scala#L40) as a starting point.

**Comment by karlhigley** [comment]
Closing and re-opening to trigger a new build.

**Comment by nihsmik** [comment]
I am sorry. I misunderstood the current behavior.

**Comment by karlhigley** [comment]
No worries! Thanks for reviewing the distance computations. I learned about `diff` from your PR.

**Comment by nihsmik** [comment]
I appreciate your kind words :)

**Pull request closed without merging**
